export const AboutData = [
  {
    type: "text",
    label: "Name",
    AttributeType: "text",
    id: "name",
    name: "name",
    placeholder: "Name",
    required: true,
  },
  {
    type: "textarea",
    label: "Description",
    textType: "textarea",
    id: "description",
    name: "description",
    placeholder: "Description",
    required: true,
    rows: 3,
    class: "form-control",
    maxLength: 2000,
  },
  {
    type: "file",
    label: "Cover Photos",
    AttributeType: "file",
    id: "image",
    name: "image",
    accept: "image/*",
    required: true,
    multiple: true,
  },
  {
    type: "price",
    label: "Price",
    AttributeType: "number",
    id: "price",
    name: "price",
    placeholder: "$Price",
    required: true,
  },
];
